@Tags(['live-stt'])
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:field_ops_copilot/engines/impl/sherpa_stt_engine.dart';
import 'package:field_ops_copilot/services/audio/mic_frame.dart';
import 'package:field_ops_copilot/services/audio/pcm_audio_format.dart';
import 'package:field_ops_copilot/services/audio/pcm_samples.dart';
import 'package:field_ops_copilot/services/audio/sherpa_recognizer.dart';
import 'package:field_ops_copilot/services/audio/spoken_digits.dart';
import 'package:field_ops_copilot/services/audio/stt_config.dart';
import 'package:field_ops_copilot/services/audio/stt_isolate_worker.dart';
import 'package:field_ops_copilot/services/rag/retrieval_router.dart';
import 'package:flutter_test/flutter_test.dart';

/// **The real recogniser, the real weights, the real fixture — on the host.**
///
/// Everything else in `test/` stops at a scripted runtime, because the native
/// library and a 43MB model are not things a unit test should need. This suite is
/// the exception, and it exists because the alternative was shipping
/// TC-STT-STRM-01 written and unrun the way Task 2.1 had to ship TC-MIC-01. It is
/// **not** a substitute for the device run — `integration_test/stt_test.dart` is
/// still owed — but it moves everything except "the arm64 device can load this"
/// from unverified to measured.
///
/// It is possible at all because `sherpa_onnx_macos` ships a macOS framework in the
/// pub cache and `SherpaRecognizerRuntime.nativeLibraryPath` can point at it. That
/// parameter exists for this and nothing else; production passes `null`.
///
/// **Opt-in, and skipped by default**, so CI stays hermetic. To run it:
///
/// ```sh
/// # 43.6MB, ungated, apache-2.0 — the same four files Task 2.0 provisions.
/// R=https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-20M-2023-02-17/resolve/main
/// mkdir -p /tmp/fieldops-stt && cd /tmp/fieldops-stt
/// for f in encoder-epoch-99-avg-1.int8.onnx decoder-epoch-99-avg-1.int8.onnx \
///          joiner-epoch-99-avg-1.int8.onnx tokens.txt; do curl -sLO "$R/$f"; done
///
/// flutter test test/services/audio/sherpa_recognizer_live_test.dart \
///   --dart-define=FIELDOPS_STT_MODEL_DIR=/tmp/fieldops-stt \
///   --dart-define=FIELDOPS_SHERPA_LIB=$HOME/.pub-cache/hosted/pub.dev/sherpa_onnx_macos-1.13.5/macos
/// ```
///
/// The skip is `String.fromEnvironment` rather than `Platform.environment` because
/// `flutter test` does not forward the shell environment to the test isolate — a
/// `--dart-define` is the only channel that reaches it.
const modelDir = String.fromEnvironment('FIELDOPS_STT_MODEL_DIR');
const sherpaLib = String.fromEnvironment('FIELDOPS_SHERPA_LIB');

/// Reads a 16-bit mono WAV and returns its PCM payload.
///
/// Parses the RIFF chunk table rather than assuming a 44-byte header. `afconvert`
/// happens to emit exactly 44 bytes here, but a fixture regenerated by any other
/// tool can carry a `LIST` chunk before `data` — and a fixed offset would then
/// feed metadata to the recogniser as audio, which transcribes as plausible
/// nonsense instead of failing.
({Uint8List pcm, int sampleRate, int channels}) readWav(String path) {
  final bytes = File(path).readAsBytesSync();
  final view = ByteData.sublistView(bytes);
  if (String.fromCharCodes(bytes.sublist(0, 4)) != 'RIFF' ||
      String.fromCharCodes(bytes.sublist(8, 12)) != 'WAVE') {
    throw FormatException('$path is not a RIFF/WAVE file');
  }

  var offset = 12;
  int? sampleRate;
  int? channels;
  int? bitsPerSample;
  while (offset + 8 <= bytes.length) {
    final id = String.fromCharCodes(bytes.sublist(offset, offset + 4));
    final size = view.getUint32(offset + 4, Endian.little);
    final body = offset + 8;
    if (id == 'fmt ') {
      channels = view.getUint16(body + 2, Endian.little);
      sampleRate = view.getUint32(body + 4, Endian.little);
      bitsPerSample = view.getUint16(body + 14, Endian.little);
    } else if (id == 'data') {
      if (bitsPerSample != 16) {
        throw FormatException('$path is $bitsPerSample-bit, expected 16');
      }
      return (
        pcm: Uint8List.sublistView(bytes, body, body + size),
        sampleRate: sampleRate!,
        channels: channels!,
      );
    }
    // Chunks are word-aligned: an odd size is followed by a pad byte.
    offset = body + size + (size.isOdd ? 1 : 0);
  }
  throw FormatException('$path has no data chunk');
}

/// Trailing silence baked into the committed fixture.
///
/// It is there because a streaming zipformer cannot emit its final words without
/// right context, and a fixture that ends mid-word would make every assertion
/// about content a test of the padding instead. Named here because one test has
/// to *remove* it to measure what the runtime's own padding does.
const fixtureTailSilence = Duration(milliseconds: 800);

/// Cuts [pcm] into frames the size the microphone delivers.
List<MicFrame> framesOf(Uint8List pcm, Duration each) {
  final size = PcmAudioFormat.sttMono16k.byteCountFor(each);
  return [
    for (var offset = 0; offset < pcm.length; offset += size)
      MicFrame(
        bytes: Uint8List.sublistView(
          pcm,
          offset,
          offset + size > pcm.length ? pcm.length : offset + size,
        ),
      ),
  ];
}

void main() {
  final skip = modelDir.isEmpty
      ? 'set --dart-define=FIELDOPS_STT_MODEL_DIR to run the live STT suite '
            '(see this file\'s doc comment)'
      : null;

  late Uint8List pcm;
  late SttConfig config;

  setUpAll(() {
    if (skip != null) return;
    final wav = readWav('test/fixtures/e102_utterance.wav');
    // The fixture's own format is asserted, not assumed: a regenerated fixture at
    // 44.1kHz stereo would otherwise be resampled by nothing and transcribe as
    // noise, and the failure would look like a model problem.
    expect(wav.sampleRate, 16000);
    expect(wav.channels, 1);
    pcm = wav.pcm;
    config = SttConfig.forInstallDirectory(modelDir).copyWith(
      // Null in production — the library is in the app bundle and is found by
      // name. On the macOS host it is not, so the whole-stack test has to say
      // where it is, and the path has to travel *in the config* because the
      // worker builds its own runtime on the far side of the isolate hop.
      nativeLibraryPath: sherpaLib.isEmpty ? null : sherpaLib,
    );
  });

  group('SherpaRecognizerRuntime', () {
    test('loads the four files and reports a load time (TC-STT-INIT-01)', () async {
      final runtime = SherpaRecognizerRuntime(
        nativeLibraryPath: sherpaLib.isEmpty ? null : sherpaLib,
      );
      addTearDown(runtime.close);

      final ready = await runtime.load(config);

      expect(ready.sampleRate, 16000);
      expect(ready.loadMillis, greaterThan(0));
      // Generous, because this is a claim about the handshake completing rather
      // than about a number: the host measured 466–471ms, and an assertion tight
      // enough to pin that would fail on a slower disk for no useful reason.
      expect(ready.loadMillis, lessThan(30000));
      // ignore: avoid_print
      print('[live] load ${ready.loadMillis}ms');
    });

    test(
      'a missing model file fails rather than producing a silent recognizer',
      () async {
        final runtime = SherpaRecognizerRuntime(
          nativeLibraryPath: sherpaLib.isEmpty ? null : sherpaLib,
        );
        addTearDown(runtime.close);

        await expectLater(
          runtime.load(SttConfig.forInstallDirectory('$modelDir/nope')),
          throwsA(anything),
        );
      },
    );

    test('the last word needs the tail padding, on audio cut at the last word', () async {
      // **The measurement the whole task turns on, stated at the width it holds
      // at.** An earlier version of this test ran the comparison over the fixture
      // as committed and the two transcripts came back *identical* — because the
      // fixture carries 0.8s of trailing silence of its own, so the runtime's
      // padding had nothing left to add. The claim "the padding recovers the last
      // word" is true of a capture that ends **at** the last word, which is what
      // `MicCapture.stop()` produces when the technician releases the button, and
      // not of a recording that already ends in silence.
      //
      // So the input here is the fixture with its trailing silence removed. That
      // is the live-microphone case, and it is the only one the padding is for.
      final cut = Uint8List.sublistView(
        pcm,
        0,
        pcm.length - PcmAudioFormat.sttMono16k.byteCountFor(fixtureTailSilence),
      );

      // A fresh runtime per run, because a reused one would carry the previous
      // utterance's decoder state into the comparison.
      final padded = await _run(config, sherpaLib, cut, pad: true);
      final unpadded = await _run(config, sherpaLib, cut, pad: false);

      // ignore: avoid_print
      print('[live] padded   "$padded"');
      // ignore: avoid_print
      print('[live] unpadded "$unpadded"');

      expect(padded, isNotEmpty);
      expect(
        padded.length,
        greaterThan(unpadded.length),
        reason:
            'the tail padding must recover audio that `inputFinished` alone does '
            'not flush — if these are equal on audio cut at the last word, '
            'SttConfig.tailPadding is dead code',
      );
      expect(
        padded.toUpperCase(),
        contains('ERROR'),
        reason: 'TC-STT-STRM-01 asks for containment of "error"',
      );
    });

    test(
      'the model emits no digits, and normalisation is what supplies them',
      () async {
        // The premise correction, run rather than argued. The vocabulary has no
        // digit tokens, so the raw transcript cannot contain "102" — and the router
        // that resolves fault codes needs digits.
        final raw = await _run(config, sherpaLib, pcm, pad: true);

        expect(
          raw,
          isNot(matches(RegExp(r'\d'))),
          reason:
              'if the model ever emits a digit, spoken_digits.dart is obsolete',
        );

        final normalized = normalizeSpokenDigits(raw);
        expect(normalized.toLowerCase(), contains('102'));
        expect(normalized.toLowerCase(), contains('error'));

        // And the end of the chain: the real router pattern over the real transcript.
        final match = RetrievalRouter.faultCodePattern.firstMatch(normalized);
        expect(match, isNotNull);
        expect(match!.group(2), '102');
      },
    );
  }, skip: skip);

  group('SherpaSttEngine over a real isolate', () {
    test('transcribes the fixture end to end (TC-STT-STRM-01)', () async {
      // The whole stack: engine → real `IsolateSttHost` → real isolate → real
      // `SherpaRecognizerRuntime` → real weights. Only the microphone is replaced,
      // by the recorded fixture cut into 100ms frames.
      //
      // This is the leg that made `SttConfig.nativeLibraryPath` necessary: the
      // worker builds its own runtime after the hop, so a library path held only
      // on the host side never reaches it, and on macOS the bare framework name
      // does not resolve. Before the path travelled in the config this test could
      // not run anywhere but a device.
      final engine = SherpaSttEngine(config: config, host: IsolateSttHost());
      addTearDown(engine.dispose);

      await engine.initialize();
      expect(engine.isReady, isTrue);
      expect(engine.ready!.sampleRate, 16000);

      final frames = framesOf(pcm, const Duration(milliseconds: 100));
      final transcripts = await engine
          .transcribe(Stream.fromIterable(frames))
          .toList();

      // ignore: avoid_print
      print(
        '[live] ${frames.length} frames in, ${transcripts.length} transcripts '
        'out, final "${transcripts.last.text}"',
      );

      // **The property, not a proxy for it — review finding R0-F2.** This used to be
      // `expect(transcripts.length, lessThan(frames.length))` under a comment claiming
      // it was "what would fail if this filter were deleted". It was not: a chunk
      // produces no text until decoding has begun, so the count is structurally below
      // the frame count whatever the filter does, and the reviewer deleted the filter
      // and watched all five tests pass at 101 → 90 transcripts.
      //
      // What the filter actually guarantees is that no partial repeats its
      // predecessor within a segment. Asserting that is asserting the thing, and it
      // fails the moment the `text != _lastEmitted` clause goes.
      // Consecutive **partials** only, and the exclusion is not a weakening — the
      // first version of this loop asserted it of every adjacent pair and failed on
      // transcript 24, which is the segment's *final* restating the last partial's
      // text. That is correct and load-bearing behaviour: a consumer needs a final to
      // commit the segment, and it carries the hypothesis it is committing. Only a
      // partial that repeats a partial is evidence the filter is gone.
      for (var i = 1; i < transcripts.length; i++) {
        final previous = transcripts[i - 1];
        final current = transcripts[i];
        if (previous.segment != current.segment) continue;
        if (current.isFinal) continue;
        expect(
          current.rawText,
          isNot(previous.rawText),
          reason:
              'partial $i repeats its predecessor verbatim, so the '
              'unchanged-hypothesis filter in _drain is not running',
        );
      }

      // And the ratio, at a bound the deletion actually crosses: 25 with the filter,
      // 90 without it, over 101 frames. Half the frame count separates those two and
      // nothing else in the pipeline sits near it.
      expect(
        transcripts.length,
        lessThan(frames.length ~/ 2),
        reason:
            'measured 25 of 101 with the filter and 90 of 101 without it; a count '
            'above half the frames means it is not filtering',
      );

      expect(transcripts, isNotEmpty);
      final last = transcripts.last;
      expect(last.isFinal, isTrue);
      expect(last.text.toLowerCase(), contains('102'));
      expect(last.text.toLowerCase(), contains('error'));
      // `rawText` is the recogniser's own output, so the normalisation above is
      // visible as a difference rather than hidden.
      expect(last.rawText, isNot(contains('102')));
    }, skip: skip);
  });
}

/// One transcription of [pcm], optionally with the tail padding.
Future<String> _run(
  SttConfig config,
  String sherpaLib,
  Uint8List pcm, {
  required bool pad,
}) async {
  final runtime = SherpaRecognizerRuntime(
    nativeLibraryPath: sherpaLib.isEmpty ? null : sherpaLib,
  );
  try {
    await runtime.load(config);
    runtime.beginSession();
    var last = '';
    for (final frame in framesOf(pcm, const Duration(milliseconds: 100))) {
      for (final t in runtime.acceptSamples(pcm16ToFloat32(frame.bytes))) {
        last = t.text;
      }
    }
    if (pad) {
      final padSamples =
          PcmAudioFormat.sttMono16k.byteCountFor(config.tailPadding) ~/ 2;
      for (final t in runtime.acceptSamples(Float32List(padSamples))) {
        last = t.text;
      }
    }
    for (final t in runtime.finishSession()) {
      last = t.text;
    }
    return last;
  } finally {
    await runtime.close();
  }
}
