/// The speech `SttConfig.primer` warms a fresh recogniser stream with.
///
/// Three properties, and each of them is something that has actually gone wrong
/// somewhere in this repo:
///
/// 1. **The asset is the head of the committed fixture**, so the audio the live
///    suite measures the remedy against is byte-for-byte the audio the app ships.
///    Extracted at authoring time rather than parsed at runtime — `lib/` has no
///    RIFF reader and does not need one — which buys a duplicate that could drift.
///    This is the check that stops it.
/// 2. **It decodes as speech**, not as silence or noise. `SttConfig.primer`'s
///    measurements say silence, white noise and a 220Hz tone all fail to prime;
///    an asset that regenerated to any of those would leave the workaround in
///    place, doing nothing, with every other test still green.
/// 3. **It survives the wire**, because it reaches the recogniser only by crossing
///    an isolate port.
library;

import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:field_ops_copilot/services/audio/pcm_audio_format.dart';
import 'package:field_ops_copilot/services/audio/pcm_samples.dart';
import 'package:field_ops_copilot/services/audio/providers.dart';
import 'package:field_ops_copilot/services/audio/stt_config.dart';
import 'package:flutter_test/flutter_test.dart';

/// The `data` chunk of a RIFF/WAVE file.
///
/// Scans the chunk table rather than assuming a 44-byte header, for the reason
/// `sherpa_recognizer_live_test.dart` gives: a fixture regenerated by another tool
/// can carry a `LIST` chunk first, and a fixed offset would then compare metadata
/// to audio and pass or fail for reasons that have nothing to do with the audio.
Uint8List wavData(String path) {
  final bytes = File(path).readAsBytesSync();
  final view = ByteData.sublistView(bytes);
  var offset = 12;
  while (offset + 8 <= bytes.length) {
    final id = String.fromCharCodes(bytes.sublist(offset, offset + 4));
    final size = view.getUint32(offset + 4, Endian.little);
    if (id == 'data') {
      return Uint8List.sublistView(bytes, offset + 8, offset + 8 + size);
    }
    offset = offset + 8 + size + (size.isOdd ? 1 : 0);
  }
  throw FormatException('$path has no data chunk');
}

void main() {
  final primer = File('assets/audio/stt_primer.pcm').readAsBytesSync();

  test('is one second of 16kHz mono audio', () {
    expect(
      primer.length,
      PcmAudioFormat.sttMono16k.byteCountFor(const Duration(seconds: 1)),
      reason:
          'the measured remedy is one second of speech; a shorter clip has not '
          'been shown to prime anything',
    );
    expect(primer.length.isEven, isTrue);
  });

  test('is the head of the fixture the live suite measures against', () {
    final fixture = wavData('test/fixtures/e102_utterance.wav');
    expect(
      primer,
      orderedEquals(Uint8List.sublistView(fixture, 0, primer.length)),
      reason:
          'the asset is extracted from the fixture rather than read from it at '
          'runtime, so nothing but this test stops the two diverging — and a '
          'primer that no longer matches what the live suite proved is a '
          'workaround nobody has measured',
    );
  });

  test('is speech, not silence and not noise', () {
    final samples = pcm16ToFloat32(primer);

    var peak = 0.0;
    for (final sample in samples) {
      final magnitude = sample.abs();
      if (magnitude > peak) peak = magnitude;
    }
    // Loud enough to be a voice rather than a room. The committed asset peaks at
    // 24282 of 32768.
    expect(peak, greaterThan(0.5), reason: 'digital silence primes nothing');

    // **How loudness *varies* over time, which is what separates speech from the
    // two things that were measured and do not prime.** The first version of this
    // test used the zero-crossing rate and was wrong: speech measures 0.306, white
    // noise 0.500 and a 220Hz tone 0.027, so the statistic is not even monotonic
    // in "speech-likeness" and no threshold on it means anything.
    //
    // Frame energy does separate them, because speech has syllables and a
    // stationary signal does not:
    //
    // ```text
    // primer       1.293
    // white noise  0.023
    // 220Hz tone   0.007
    // ```
    //
    // Two orders of magnitude, which is why the bound below can sit an order away
    // from both sides and still be a real assertion.
    const frame = 320; // 20ms at 16kHz.
    final rms = <double>[];
    for (var start = 0; start + frame <= samples.length; start += frame) {
      var energy = 0.0;
      for (var i = start; i < start + frame; i++) {
        energy += samples[i] * samples[i];
      }
      rms.add(math.sqrt(energy / frame));
    }
    final mean = rms.reduce((a, b) => a + b) / rms.length;
    final variance =
        rms.map((r) => (r - mean) * (r - mean)).reduce((a, b) => a + b) /
        rms.length;

    expect(
      math.sqrt(variance) / mean,
      greaterThan(0.5),
      reason:
          'a flat energy envelope is a tone or noise, and both were measured '
          'against the real recogniser and neither primes it',
    );
  });

  test('survives the isolate wire that carries it to the worker', () {
    // The primer reaches the recogniser only by crossing a port, so a config that
    // drops or mangles it on the way is the whole failure — silently, because a
    // recogniser with no primer transcribes fine apart from the first word.
    final config = SttConfig.forInstallDirectory(
      '/models/stt',
    ).copyWith(primer: primer);

    final restored = SttConfig.fromWire(config.toWire());

    expect(restored.primer, orderedEquals(primer));
  });

  test('an absent primer is a config, not a failure', () {
    final bare = SttConfig.forInstallDirectory('/models/stt');
    expect(bare.primer, isNull);
    expect(SttConfig.fromWire(bare.toWire()).primer, isNull);
  });

  test('a half-sample primer is rejected rather than fed as noise', () {
    final wire = SttConfig.forInstallDirectory('/models/stt').toWire()
      ..['primer'] = Uint8List.fromList([1, 2, 3]);

    expect(
      () => SttConfig.fromWire(wire),
      throwsA(isA<FormatException>()),
      reason:
          'an odd length means the buffer was cut mid-sample, and priming the '
          'encoder with noise is worse than not priming it at all',
    );
  });

  test('the asset path is the one pubspec declares', () {
    expect(sttPrimerAsset, 'assets/audio/stt_primer.pcm');
    expect(
      File('pubspec.yaml').readAsStringSync(),
      contains('- $sttPrimerAsset'),
      reason:
          'an asset that is not declared is not bundled, and `_loadPrimer` '
          'answers null rather than throwing — so the failure would be a device '
          'that quietly stops priming and mis-hears first words again',
    );
  });
}
